name: Build and Lint

on:
  push:
    branches: [ master, develop ]
    paths: [ src/**, .github/workflows/build.yml ]
  pull_request:
    branches: [ master, develop ]
    paths: [ src/** ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        env:
          CI: true


  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # the Node.js versions to build on
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint
